logging:
  level:
    io:
      spring:
        cloud:
          samples: DEBUG

fortune:
  fallbackFortune: The fog should lift today. Maybe.

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
